name: codersquare CI

on: [ push ]

jobs:
  images_build:
    runs-on: ubuntu-latest
    steps:
    - name: clone the repo
      uses: actions/checkout@v3

    - name: run eslint
      uses: synergy-au/eslint-action@v1
      with: 
        rules-path: './.eslintrc.ci.js'
        setup-from-package-json: 'true'

    - name: run unit tests
      run: |
        npm install
        npm test

    - name: build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: islamwalid/codersquare
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
